- hosts: librad
  gather_facts: no
  roles:
  - role: libra
    vars:
      target: edge
      image: docker.dev.com/librad
      etcd_endpoints: http://192.168.10.31:2379
      envoy_config_template: envoy/edge.template.yaml
      runtimes: runtime_edge
      ports: [ "10000:10000" ]
      command: "/bin/sleep infinity"
