# Bootstrap of edge proxy
#
# Configuring envoy as an edge proxy:
# https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge.html

node:
  id: edgeproxy
  cluster: cluster_edgeproxy

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8000

static_resources:
# secrets:
# - name: edge_cert
#   tls_certificate:
#     certificate_chain:
#       filename: certs/server.cert.pem
#     private_key:
#       filename: certs/server.key.pem
# - name: validation_context
#   validation_context:
#     trusted_ca:
#       filename: certs/ca.cert.pem

dynamic_resources:
  cds_config:
    path: /etc/envoy/cds.yaml
  lds_config:
    path: /etc/envoy/lds.yaml

overload_manager:
  refresh_interval: 0.25s
  resource_monitors:
  - name: "envoy.resource_monitors.fixed_heap"
    typed_config:
      "@type": type.googleapis.com/envoy.config.resource_monitor.fixed_heap.v2alpha.FixedHeapConfig
      # TODO: Tune for your system.
      max_heap_size_bytes: 2147483648 # 2 GiB
  actions:
  - name: "envoy.overload_actions.shrink_heap"
    triggers:
    - name: "envoy.resource_monitors.fixed_heap"
      threshold:
        value: 0.95
  - name: "envoy.overload_actions.stop_accepting_requests"
    triggers:
      - name: "envoy.resource_monitors.fixed_heap"
        threshold:
          value: 0.98

layered_runtime:
  layers:
  - name: runtime_edge
    static_layer:
      envoy:
        resource_limits:
          listener:
            listener_edge_ingress:
              connection_limit: 10000
      overload:
        global_downstream_max_connections: 50000

