apiVersion: v1
kind: Service
metadata:
  name: {{ include "edgeproxy.name" . }}
  namespace: {{ include "edgeproxy.namespace" . }}
  labels:
    {{- include "edgeproxy.labels" . | nindent 4 }}
  annotations:
    # use existed tencent cloud CLB to expose services
    service.kubernetes.io/tke-existed-lbid: lb-xxxxxxxx
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "edgeproxy.selectorLabels" . | nindent 4 }}

