# 此配置只用于开发环境快速搭建，生产环境请使用外部实例。

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: dev
  labels:
    app: redis
spec:
  clusterIP: None # headless
  ports:
  - port: 6379
    #name: redis
  selector:
    app: redis
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: dev
  labels:
    app: redis
spec:
  replicas: 3
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4.0-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: etc
          mountPath: /etc/redis.conf
          subPath: redis.conf
          readOnly: true
        - name: data
          mountPath: /data
        args: ["redis-server", "/etc/redis.conf"]
      volumes:
      - name: etc
        configMap:
          name: redis
      - name: data
        emptyDir: {}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: dev
data:
  redis.conf: |
    maxmemory 100mb
    maxmemory-policy volatile-lru
    lua-time-limit 1000
---
