apiVersion: v1
kind: Service
metadata:
  name: {{ include "apiproxy.name" . }}
  namespace: {{ include "apiproxy.namespace" . }}
  labels:
    {{- include "apiproxy.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "apiproxy.selectorLabels" . | nindent 4 }}

