- name: create /data/etcd directory
  file:
    path: /data/etcd
    state: directory
    mode: '0755'

- name: etcd service
  docker_container:
    name: etcd
    image: mirrorgooglecontainers/etcd:3.3.17
    restart_policy: unless-stopped
    state: "{{ container_state }}"
    restart: "{{ container_restart|default('no') }}"
    recreate: "{{ container_recreate|default('no') }}"
    ports:
      - "2379:2379"
      #- "2380:2380"
    volumes:
      - "/data/etcd:/data/etcd"
    command: "/usr/local/bin/etcd \
              --name s1 \
              --data-dir /data/etcd \
              --listen-client-urls http://0.0.0.0:2379 \
              --advertise-client-urls http://0.0.0.0:2379"

- name: setup subnet
  shell: docker exec etcd etcdctl set /libra.net/network/config '{"Network":"10.5.0.0/16","Backend":{"Type":"vxlan"}}'

