# setup flannel

- name: unarchive flannel
  unarchive:
    src: flannel-v0.12.0-linux-amd64.tar.gz
    dest: /tmp/
    creates: /tmp/flanneld

- name: check if flannel is running
  command: pgrep flanneld
  failed_when: false
  changed_when: false
  register: flanneld_status

- name: stop flanneld
  shell: |
    killall flanneld
  register: killall_status
  when: flanneld_status.rc != 0
  failed_when: false
  changed_when: killall_status.rc == 0

- name: start flannel
  shell: |
    nohup /tmp/flanneld -ip-masq -etcd-prefix '/libra.net/network' -etcd-endpoints {% for item in groups['etcd'] %}http://{{ item }}:2379,{% endfor %} >/tmp/flanneld.log 2>&1 &
  when: flanneld_status.rc != 0

