# Default values for libra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

librad:
  replicaCount: 1

  image:
    pullPolicy: IfNotPresent
    repository: onemore/librad
    tag: "0.0.1"

  resource: {}

syncer:
  image:
    repository: onemore/librad
    pullPolicy: IfNotPresent
    tag: "0.0.2"

  resources: {}

apiproxy:
  replicaCount: 1

  service:
    nodePort: 31080

  resource: {}

edgeproxy:
  replicaCount: 1

  service:
    nodePort: 30080

  resources: {}
 
