# CDS for dynamic cluster configuration

resources:

- name: cluster_librad_v1
  "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  connect_timeout: 0.2s
  http2_protocol_options: {}
  type: LOGICAL_DNS
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: cluster_librad_v1
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: librad-v1.libra.svc.cluster.local
              port_value: 80
  #health_checks:
  #- timeout: 0.2s
  #  interval: 1s
  #  healthy_threshold: 1
  #  unhealthy_threshold: 3
  #  grpc_health_check: {}

