version: "3.2"

services:
  mongo:
    container_name: libra-mongo
    image: mongo:3.6
    volumes:
      - mongo-db:/data/db
      - mongo-configdb:/data/configdb

  redis1:
    container_name: libra-redis1
    image: redis:5.0
  redis2:
    container_name: libra-redis2
    image: redis:5.0
  redis3:
    container_name: libra-redis3
    image: redis:5.0

  envoy:
    container_name: libra-envoy
    image: libra-envoy
    build: { context: envoy }
    depends_on:
      - mongo
      - redis1
      - redis2
      - redis3
    ports:
      - "8000:8000"   # envoy admin
      - "10000:10000"

  librad:
    container_name: libra-librad
    image: ntons/librad:latest
    depends_on:
      - envoy
    environment:
      LIBRAD_BIND:                      :80
      LIBRAD_PORTAL_REDIS:              redis://libra-envoy:6379
      LIBRAD_PORTAL_MONGO:              mongodb://libra-envoy:27017/libra
      LIBRAD_GATEWAY_BROADCAST_REDIS:   redis://libra-redis1:6379/1
      LIBRAD_DATABASE_REMON_REDIS:      redis://libra-envoy:6379
      LIBRAD_DATABASE_REMON_MONGO:      mongodb://libra-envoy:27017
      LIBRAD_DATABASE_DISTLOCK_REDIS:   redis://libra-envoy:6379
      LIBRAD_RANKING_BUBBLE_REDIS:      redis://libra-envoy:6379
      LIBRAD_RANKING_LEADERBOARD_REDIS: redis://libra-envoy:6379

  echo:
    container_name: libra-echo
    image: libra-echo
    build: { context: echo }
    depends_on:
      - librad

volumes:
  mongo-db:
  mongo-configdb:

