- name: create /data/mongo/db directory
  file:
    path: /data/mongo/db
    state: directory
    mode: '0755'

- name: create /data/mongo/configdb directory
  file:
    path: /data/mongo/configdb
    state: directory
    mode: '0755'

- name: mongo service
  docker_container:
    name: mongo
    image: mongo:3.6
    restart_policy: unless-stopped
    state: "{{ container_state }}"
    restart: "{{ container_restart|default('no') }}"
    recreate: "{{ container_recreate|default('no') }}"
    ports:
      - "27017:27017"
    volumes:
      - "/data/mongo/db:/data/db"
      - "/data/mongo/configdb:/data/configdb"

