apiVersion: v1
kind: Service
metadata:
  name: libra-mongo
  namespace: dev
  labels:
    app: libra-mongo
spec:
  ports:
  - port: 27017
    #name: mongo
  selector:
    app: libra-mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: libra-mongo
  namespace: dev
  labels:
    app: libra-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libra-mongo
  template:
    metadata:
      labels:
        app: libra-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:3.6
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
---
