# Gateway for clients accessing libra

apiVersion: v1
kind: Service
metadata:
  name: edgeproxy
  namespace: libra
  labels:
    app: edgeproxy
spec:
  ports:
  - port: 80
    name: grpc
    nodePort: 30080
  type: NodePort # expose service by NodePort
  selector:
    app: edgeproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgeproxy
  namespace: libra
  labels:
    app: edgeproxy
spec:
  selector:
    matchLabels:
      app: edgeproxy
  replicas: 2
  template:
    metadata:
      labels:
        app: edgeproxy
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.14.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 8000
        volumeMounts:
        - name: config
          mountPath: /etc/envoy
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: edgeproxy
---
