apiVersion: v1
kind: Service
metadata:
  name: {{ include "librad.name" . }}
  namespace: {{ include "librad.namespace" . }}
  labels:
    {{- include "librad.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "librad.selectorLabels" . | nindent 4 }}

