apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    app: redis-server
spec:
  ports:
  - port: 6379
    name: tcp
    appProtocol: redis
  selector:
    app: redis-server
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  labels:
    app: redis-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
      - name: redis
        image: redis:5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: redis-server
spec:
  host: redis-server.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash: {}
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis-server
spec:
  hosts:
  - redis-server.default.svc.cluster.local
  tcp:
  - match:
    - port: 6379
    route:
    - destination:
        host: redis-server.default.svc.cluster.local
---

